//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzoteka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muzotekaEntities : DbContext
    {
        public muzotekaEntities()
            : base("name=muzotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrator { get; set; }
        public virtual DbSet<album> album { get; set; }
        public virtual DbSet<ocena_utwor> ocena_utwor { get; set; }
        public virtual DbSet<playlista> playlista { get; set; }
        public virtual DbSet<utwor> utwor { get; set; }
        public virtual DbSet<utwor_w_playlista> utwor_w_playlista { get; set; }
        public virtual DbSet<uzytkownik> uzytkownik { get; set; }
        public virtual DbSet<wykonawca> wykonawca { get; set; }
    }
}
