//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzoteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utwor_w_playlista
    {
        public int utwor_id { get; set; }
        public int playlista_id { get; set; }
    
        public virtual playlista playlista { get; set; }
    }
}
