//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzoteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uzytkownik()
        {
            this.ocena_utwor = new HashSet<ocena_utwor>();
            this.playlista = new HashSet<playlista>();
        }
    
        public int id { get; set; }
        [Display(Name = "Login")]
        [Required]
        public string login { get; set; }
        [Display(Name = "Hasło")]
        [Required]
        public string password { get; set; }
        public string uprawnienia { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Oceny utworów")]
        public virtual ICollection<ocena_utwor> ocena_utwor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Playlisty")]
        public virtual ICollection<playlista> playlista { get; set; }
    }
}
